services:
  patient-service:
    build:
      context: ./patient-service
    container_name: patient-service
    ports:
      - "8080:8080"
    depends_on:
      - patient-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-db:5432/patientdb
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - microservice-net

  appointment-service:
    build:
      context: ./appointment-service
    container_name: appointment-service
    ports:
      - "8081:8080"
    depends_on:
      - patient-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-db:5432/appointmentdb
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - microservice-net

  patient-db:
    image: postgres:15
    container_name: patient-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - patient-db-data:/var/lib/postgresql/data
    networks:
      - microservice-net

volumes:
  patient-db-data:

networks:
  microservice-net:
    driver: bridge
