services:
  patient-service:
    build:
      context: ./patient-service
    container_name: patient-service
    ports:
      - "4000:4000"
    depends_on:
      - patient-db
      - billing-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_KAFKA_BOOTSTRAP_SERVERS: Kafka:9092
    networks:
      - microservice-net
  billing-service:
    build:
      context: ./billing-service
    container_name: billing-service
    ports:
      - "4001:4001" #Rest API
      - "9001:9001" #grpc
    networks:
      - microservice-net
#  appointment-service:
#    build:
#      context: ./appointment-service
#    container_name: appointment-service
#    ports:
#      - "8081:8080"
#    depends_on:
#      - patient-db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-db:5432/appointmentdb
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#    networks:
#      - microservice-net

  patient-db:
    image: postgres
    container_name: patient-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - patient-db-data:/var/lib/postgresql/data
    networks:
      - microservice-net
  analytics-service:
    build:
      context: ./analytics-service
    container_name: analytics-service
    ports:
      - "4002:4002"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: Kafka:9092
    networks:
      - microservice-net
  kafka:
   image: bitnami/kafka:latest
   container_name: kafka
   ports:
     - "9092:9092"  # Internal broker
     - "9094:9094"  # External client
   environment:
     KAFKA_CFG_PROCESS_ROLES: controller,broker
     KAFKA_CFG_NODE_ID: 0
     KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
     KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
     KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
     KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
     KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
     KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
   networks:
    - microservice-net
volumes:
  patient-db-data:

networks:
  microservice-net:
    driver: bridge
