services:
  patient-service:
    build:
      context: ./patient-service
    container_name: patient-service
    ports:
      - "4000:4000"
    depends_on:
      - patient-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - microservice-net
  billing-service:
    build:
      context: ./billing-service
    container_name: billing-service
    ports:
      - "4001:4001" #Rest API
      - "9001:9001" #grpc

    networks:
      - microservice-net
#  appointment-service:
#    build:
#      context: ./appointment-service
#    container_name: appointment-service
#    ports:
#      - "8081:8080"
#    depends_on:
#      - patient-db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-db:5432/appointmentdb
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#    networks:
#      - microservice-net

  patient-db:
    image: postgres
    container_name: patient-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - patient-db-data:/var/lib/postgresql/data
    networks:
      - microservice-net

volumes:
  patient-db-data:

networks:
  microservice-net:
    driver: bridge
